### ISSUE TITLE
Enable YARN UI2

### ISSUE THREAD

**Issue by AtticusJoy** [panovvv/hadoop-hive-spark-docker#1]
I'd love to have access to the new UI (UI2) that was built for the YARN resource manager in your docker distribution of hadoop-hive-spark. There are notes for it in the most recent release (https://hadoop.apache.org/docs/r3.2.2/hadoop-yarn/hadoop-yarn-site/YarnUI2.html). While there is not this documentation for the property that is mentioned, I did find `yarn.webapp.ui2.enable` is available in the `yarn-default.xml` in the 3.2.0 release of Hadoop (https://hadoop.apache.org/docs/r3.2.0/hadoop-yarn/hadoop-yarn-common/yarn-default.xml). So, I'm wondering if just flipping the flag to true will give access to the new UI at localhost:8088/ui2/#/cluster-overview . It's a really nice re-work of the YARN RM UI and if it's that easy, them maybe not too time consuming of a feature.

**Comment by panovvv** [comment]
Splendid idea! Thanks for the tip. I've added this in version 2.5.1

**Comment by panovvv** [comment]
Splendid idea! Thanks for the tip. I've added this in version 2.5.1
